name: Elixir New
url: http://zhongwencool.github.io/
description: All about Elixir&Erlang

permalink: :title/
paginate: 10
highlighter: rouge
gems: [jekyll-paginate]

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
